---
branches:
- main
projects:
  XAuth:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
      - src: SOFe/await-generator
        version: ^3.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
