name: XAuth
version: 1.0.0
main: Luthfi\XAuth\Main
api: 5.0.0
authors: [ChernegaSergiy, Luthfi]
description: "A simple, secure, and extensible authentication plugin for PocketMine-MP, modernized for 2FA integration."
website: https://github.com/newlandpe/XAuth
softdepend: ["PlaceholderAPI", "ScoreHud"]

permissions:
  xauth.command.register:
    description: "Allow player to register an account"
    default: true
  xauth.command.login:
    description: "Allow player to login to their account"
    default: true
  xauth.command.resetpassword:
    description: "Allow player to reset their password"
    default: true
  xauth.command.logout:
    description: "Allow player to logout from their account"
    default: true
  xauth.command.unregister:
    description: "Allow player to unregister their own account"
    default: true
  xauth.command.admin:
    description: "Allows usage of the /xauth command"
    default: op
