# Configuration for XAuth

# Available languages: en
language: en

# Enable titles on join
enable_titles: true

# Defines the order of authentication steps.
# Only steps registered by plugins (e.g., "captcha_login", "binding_manager_2fa") will be executed.
# If a step listed here is not registered by any plugin, it will be skipped.
# Built-in steps include "auto_login", "xauth_login", and "xauth_register".
authentication-flow-order:
  - "captcha_login"
  - "auto_login"
  - "xauth_login"
  - "xauth_register"
  - "binding_manager_2fa"

# Auto-login settings
auto-login:
  enabled: true
  # Security level for auto-login. To disable auto-login, set `enabled: false` above.
  # 0: Low - Auto-login is based on IP address only. Works for players behind NAT, but less secure if multiple people share the same public IP.
  # 1: High (Recommended) - Auto-login is based on a combination of IP address and a unique Device ID. More secure.
  security_level: 1
  lifetime_seconds: 2592000 # 30 days
  refresh_session_on_login: true # If true, the session lifetime will be extended on each successful auto-login.
  max_sessions_per_player: 5
  cleanup_interval_minutes: 60 # Run cleanup every hour

# Password complexity requirements
password_complexity:
  min_length: 8
  max_length: 64
  require_uppercase: true
  require_lowercase: true
  require_number: true
  require_symbol: false
  # Enable checking against a list of common/weak passwords.
  enable_weak_password_check: true
  # Path to the file containing a list of weak passwords (one password per line).
  weak_password_list_file: "weak_passwords.txt"

# Password hashing settings
password_hashing:
  # Available algorithms: BCRYPT, ARGON2ID, ARGON2I
  # BCRYPT is generally recommended for most use cases.
  # ARGON2ID is a newer, more memory-hard algorithm that offers stronger protection against GPU attacks.
  # ARGON2I is a variant of Argon2 optimized for defense against side-channel attacks.
  algorithm: BCRYPT
  options:
    # Options for BCRYPT algorithm
    # cost: The algorithmic cost that should be used. Ranges from 4 to 31.
    # Higher cost means more secure but slower hashing. Recommended: 10-12.
    BCRYPT:
      cost: 10
    # Options for ARGON2ID algorithm
    # memory_cost: Maximum memory (in kibibytes) that Argon2 will use. Default: 65536 (64MB).
    # time_cost: Maximum amount of time (in iterations) that Argon2 will spend. Default: 4.
    # threads: Number of threads that Argon2 will use. Default: 1.
    ARGON2ID:
      memory_cost: 65536
      time_cost: 4
      threads: 1
    # Options for ARGON2I algorithm
    # memory_cost: Maximum memory (in kibibytes) that Argon2 will use. Default: 65536 (64MB).
    # time_cost: Maximum amount of time (in iterations) that Argon2 will spend. Default: 4.
    # threads: Number of threads that Argon2 will use. Default: 1.
    ARGON2I:
      memory_cost: 65536
      time_cost: 4
      threads: 1

forms:
  enabled: false
  kick-on-close: false # Kick player if they close the auth form without logging in
  register:
    rules_toggle:
      enabled: true

# Database configuration
database:
  # Available types: sqlite, mysql
  # sqlite is suitable for most servers. mysql is recommended for large-scale production environments.
  type: sqlite
  sqlite:
    file: "data.sqlite" # Path to the SQLite database file
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: ""
    schema: xauth
    socket: "" # Optional: Path to the MySQL socket file (e.g., /var/run/mysqld/mysqld.sock)
    ssl: # Optional: SSL/TLS connection settings
      enabled: false # Set to true to enable SSL/TLS
      key: "" # Path to the client private key file
      certificate: "" # Path to the client certificate file
      ca-certificate: "" # Path to the CA certificate file
      ca-path: "" # Path to a directory containing trusted CA certificates
      cipher-algorithms: "" # List of allowable ciphers (e.g., DHE-RSA-AES256-SHA)
  log_queries: false # Set to true to log all database queries at DEBUG level (useful for debugging)

# Enable or disable data migration.
# If true, XAuth will attempt to migrate data from older formats (e.g., players.yml)
# to the currently configured database provider on startup.
# It's recommended to disable this after the initial migration is complete.
enable_migration: false

# Brute-force protection settings
bruteforce_protection:
  enabled: true
  max_attempts: 5
  block_time_minutes: 10
  # Kick the player immediately when they run out of login attempts.
  kick_on_block: true
  # (Recommended) Kick already-blocked players before they fully join the server.
  kick_at_pre_login: true

command_settings:
  # If enabled, the /xauth forcepasswordchange command will immediately affect an online player.
  # If disabled, it will only take effect on their next login.
  force_change_immediate: true
  # Allow players to use the /logout command.
  allow_logout_command: true
  # Allow players to unregister their own account using /unregister.
  allow_player_self_unregister: true

session:
  # The time in seconds a player has to log in before being kicked. Set to 0 to disable.
  login-timeout: 30

# IP address limits
ip_limits:
  # Maximum number of registrations per IP address. 0 to disable.
  max_registrations_per_ip: 0
  # Maximum number of connections per IP address. 0 to disable.
  max_joins_per_ip: 0

# Restrictions for unauthenticated players
restrictions:
  # Allow player to chat.
  allow_chat: false
  # Allow player to move. If false, the player will be frozen.
  allow_movement: true
  # Allow player to receive damage.
  allow_damage_receive: false
  # Allow player to deal damage.
  allow_damage_deal: false
  # Allow player to break blocks.
  allow_block_breaking: false
  # Allow player to place blocks.
  allow_block_placing: false
  # Allow player to drop items.
  allow_item_dropping: false
  # Allow player to interact with blocks (e.g., open chests, doors).
  allow_block_interaction: false
  # Allow player to use items.
  allow_item_use: false
  # Allow player to pick up items from the ground.
  allow_item_pickup: false
  # Allow player to open inventories (chests, furnaces, etc.).
  allow_inventory_open: false
  # Allow player to move items within an open inventory.
  # This only has an effect if allow_inventory_open is true.
  allow_inventory_transaction: false
  # Allow player to craft items.
  allow_crafting: false
  # A list of commands that unauthenticated players are allowed to use.
  # Commands must not start with a forward slash (/).
  # Use lowercase for all commands.
  allowed_commands:
    - login
    - register

# Player state protection settings (on join, before authentication)
protection:
  # Force player into survival mode until they log in.
  force_survival: true

  # Teleport player to a safe location until they log in.
  teleport:
    enabled: true
    # If true, the player will be teleported back to their original position after login.
    # If false, they will remain at the spawn location.
    return_to_original_position: true
    world: "world"
    coords:
      x: 128.5
      y: 70.0
      z: 128.5

  # Protects and hides the player's full state (inventory, armor, off-hand,
  # effects, health, xp) until they log in.
  protect_player_state: true

# In-world visibility settings for unauthenticated players.
in_world_visibility:
  # Method to use for making the player's model invisible.
  # "packets": True invisibility. Hides the player entity completely. (Recommended)
  # "effect": Applies the standard invisibility potion effect.
  # "none": Player model is fully visible.
  mode: "packets"
  # true - hide other players from unauthenticated players.
  # false - show other players to unauthenticated players.
  hide_others_from_unauthenticated: true

# Player list (Tab) visibility for unauthenticated players.
player_list_visibility:
  # If true, the player will be hidden from the player list (Tab).
  # This is independent of the in-world visibility mode.
  hide: true
  # true - hide other players from unauthenticated players in the player list (Tab).
  # false - show other players to unauthenticated players in the player list (Tab).
  hide_others_from_unauthenticated: false

# Apply blindness effect to the unauthenticated player.
apply_blindness: true

# GeoIP Protection
geoip:
  enabled: false
  # Available modes: blacklist, whitelist
  mode: "blacklist"
  # List of country codes (e.g., RU, BY, CN) or "LOCALHOST" for local network connections.
  country-list: []
  network:
    force-resolve-hosts:
      # Example: "ip-api.com": "208.95.112.1"
    custom-ca-bundle: ""

# WaterdogPE Fix settings
waterdog-fix:
  enabled: false
  # If true, players not authenticated to WaterdogPE (i.e., missing Waterdog_XUID/IP in JWT) will be kicked.
  force-players-to-waterdog: false
  # The IP address WaterdogPE is bound to on the PocketMine-MP server.
  # This is used to verify the connection is coming from WaterdogPE.
  waterdog-bind-address: "127.0.0.1"

# Do not change this
config-version: 1.3
