# Configuration for XAuth

# Available languages: en
language: en

# Enable titles on join
enable_titles: true

# Auto-login settings
auto-login:
  enabled: true
  lifetime_seconds: 2592000 # 30 days
  refresh_session_on_login: true # If true, the session lifetime will be extended on each successful auto-login.
  max_sessions_per_player: 5
  cleanup_interval_minutes: 60 # Run cleanup every hour

# Password complexity requirements
password_complexity:
  min_length: 8
  max_length: 64
  require_uppercase: true
  require_lowercase: true
  require_number: true
  require_symbol: false

forms:
  enabled: false
  kick-on-close: false # Kick player if they close the auth form without logging in
  register:
    rules_toggle:
      enabled: true

# Database configuration
database:
  # Available providers: yaml, json, sqlite, mysql
  # sqlite is recommended for all servers. yaml is not suitable for production due to performance and data corruption risks.
  provider: sqlite
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: ""
    database: xauth

# Brute-force protection settings
bruteforce_protection:
  enabled: true
  max_attempts: 5
  block_time_minutes: 10
  # Kick the player immediately when they run out of login attempts.
  kick_on_block: true
  # (Recommended) Kick already-blocked players before they fully join the server.
  kick_at_pre_login: true

command_settings:
  # If enabled, the /xauth forcepasswordchange command will immediately affect an online player.
  # If disabled, it will only take effect on their next login.
  force_change_immediate: true

session:
  # The time in seconds a player has to log in before being kicked. Set to 0 to disable.
  login-timeout: 30

# Do not change this
config-version: 1.0
